CREATE TABLE [dbo].[Teams] (
	Id VARCHAR(50) PRIMARY KEY,
	TeamNumber INT NOT NULL,
	Nickname VARCHAR(255) NULL,
	Name VARCHAR(MAX) NOT NULL,
	SchoolName VARCHAR(MAX) NULL,
	City VARCHAR(255) NULL,
	StateProv VARCHAR(255) NULL,
	Country VARCHAR(255) NULL,
	Address VARCHAR(MAX) NULL,
	PostalCode VARCHAR(50) NULL,
	LocationName VARCHAR(MAX) NULL,
	Website VARCHAR(MAX) NULL,
	RookieYear INT NULL,
    CreatedBy int NULL,
    CreatedAt datetime2 NULL DEFAULT sysdatetime(),
    ModifiedBy int NULL,
    ModifiedAt datetime2 NULL,
    RowVersion timestamp NOT NULL
);