CREATE TABLE Matches (
	_key VARCHAR(50) PRIMARY KEY,
	match_number INT NOT NULL,
	red_1 VARCHAR(50) NULL FOREIGN KEY REFERENCES Teams(_key),
	red_2 VARCHAR(50) NULL FOREIGN KEY REFERENCES Teams(_key),
	red_3 VARCHAR(50) NULL FOREIGN KEY REFERENCES Teams(_key),
	blue_1 VARCHAR(50) NULL FOREIGN KEY REFERENCES Teams(_key),
	blue_2 VARCHAR(50) NULL FOREIGN KEY REFERENCES Teams(_key),
	blue_3 VARCHAR(50) NULL FOREIGN KEY REFERENCES Teams(_key),
	event_key VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES Events(_key),
	red_score INT NULL,
	blue_score INT NULL,
	winning_alliance VARCHAR(10) NULL,
	time DATETIME NULL,
	actual_time DATETIME NULL,
	predicted_time DATETIME NULL
);