CREATE TABLE Notes (
	_id INT IDENTITY(0,1) PRIMARY KEY,
	team_key VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES Teams(_key),
	event_key VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES Events(_key),
	scout_name VARCHAR(255) NOT NULL,
	text VARCHAR(MAX) NOT NULL
);